### ISSUE TITLE
Error querying APPL

### ISSUE THREAD

**Issue by rdiasfreitas** [lukaszbanasiak/yahoo-finance#10]
AAPL seems to have no 'LastTrade', it;s breaking the code when starting Share('APPL').

**Comment by lukaszbanasiak** [comment]
There is no `LastTrade` key in the data set.
There is only `LastTradeDate`, `LastTradeTime` and `LastTradeDateTimeUTC`

You can preview all the data caling `data_set` attr on obj:

    >>>Share('APPL').data_set
    {u'YearLow': u'0.00', u'OneyrTargetPrice': None, u'DividendShare': u'0.00', (...)
