### ISSUE TITLE
get_historical() method gives error when stock does not have any data from start date

### ISSUE THREAD

**Issue by hannanp9** [lukaszbanasiak/yahoo-finance#106]
The method should get the oldest details of the stock even if there is no any data for the start date specified. Is there any workaround? 

Can someone help to resolve this please.

**Comment by tchellomello** [comment]
@hannanp9  could you please share the traceback that you are hitting?

**Comment by hannanp9** [comment]
Traceback (most recent call last):

  File "<ipython-input-6-f554f69d696d>", line 7, in <module>
    dataList =  obj.get_historical('2016-01-01','2017-02-12')

  File "/Users/abdulhannanpatel/anaconda/lib/python3.5/site-packages/yahoo_finance/__init__.py", line 342, in get_historical
    result = self._request(query)

  File "/Users/abdulhannanpatel/anaconda/lib/python3.5/site-packages/yahoo_finance/__init__.py", line 125, in _request
    raise YQLResponseMalformedError()

YQLResponseMalformedError: Response malformed.

**Comment by hannanp9** [comment]
You need to run below line of code to reproduce the error --

obj = Share('D20.AX')
dataList = obj.get_historical('2016-01-01','2017-02-12')

I am lagging with the time, quick response is appreciated. Thanks.

**Comment by tchellomello** [comment]
@hannanp9  I think this is working as expected.  I tried to find this company stock and without any luck. 

What kind of history are you expecting?

**Comment by hannanp9** [comment]
I am trying to get historical data for past one year. As i said it works for those stocks which have history of more than a year but for those who came to the market before one year- like 'D20.AX', the get_historical() throws an error. Can it not be possible to get the the data from its inception even if I pass time duration of one year to the function?

**Comment by inigohrey** [comment]
What he means is this ticker (D20.AX) is not on Yahoo Finance's database. If it can't be found, no history can be given.

**Comment by hannanp9** [comment]
I have checked it again. The function is now working fine. Thanks @tchellomello @inigohrey

**Comment by tchellomello** [comment]
@hannanp9  nice that you figured out. Could you please close this issue if everything is working fine for you? 

Thank you
