### ISSUE TITLE
yql.YQLQuery() problem

### ISSUE THREAD

**Issue by AlanRufus** [lukaszbanasiak/yahoo-finance#125]
Not sure if it is related the recent Yahoo Finance Upgrade..but I got error 
http_error_default raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 500: Server Error.
Is this the same as the yql.YQLQuery() problem?

This lib works perfectly until this Monday, I truly hope it is just a simple or temporary problem that can be fixed quickly.

**Comment by lukaszbanasiak** [comment]
Please see this issue https://github.com/lukaszbanasiak/yahoo-finance/issues/44
