### ISSUE TITLE
yahoo.finance.YQLRResponseMalformedError: Response Malformed

### ISSUE THREAD

**Issue by pepehernandez** [lukaszbanasiak/yahoo-finance#129]
keep getting:
"...__init__.py", line 342, in get_historical result = self.request(query)
"...__init__.py", line  125, in_request raise YQLResponseMalformedError() 
yahoo_finance. YQLResponseMalformed Error: Response malformed.

Tried many many times but keep getting same error. Anybody know anything about this?  Yahoo error? Below is the code I used. 

from pprint import pprint
from yahoo_finance import Share
symbol = raw_input("Enter stock symbol: ")
stock = Share(symbol)

first = raw_input("Enter start date ymd xxxx-xx-xx: ")
second = raw_input ("Enter end date ymd xxxx-xx-xx: ")
pprint(stock.get_historical(first, second))

**Comment by madc0ww** [comment]
@pepehernandez It seems that this issue is the same than Issue #128 , and there is a **Yahoo Finance**  server down, which is the one where the library gets the data.
