### ISSUE TITLE
YQLResponseMalformedError: Response malformed - 06/11/2017

### ISSUE THREAD

**Issue by JulianStorz** [lukaszbanasiak/yahoo-finance#141]
Hi All
Since maybe two or three days, I do get this Error message when using Share("TICKER_NAME"):

`Traceback (most recent call last):
>   File "C:\Users\Julian\Anaconda3\lib\site-packages\yahoo_finance\__init__.py", line 120, in _request
>     _, results = response['query']['results'].popitem()
> AttributeError: 'NoneType' object has no attribute 'popitem'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "C:\Users\Julian\Anaconda3\lib\site-packages\yahoo_finance\__init__.py", line 123, in _request
>     raise YQLQueryError(response['error']['description'])
> KeyError: 'error'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "C:\Users\Julian\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2881, in run_code
>     exec(code_obj, self.user_global_ns, self.user_ns)
>   File "<ipython-input-137-b39db1fe6afa>", line 1, in <module>
>     apple = Stock_Analysis("AAPL","2015-01-01")
>   File "<ipython-input-136-1d74432311a1>", line 6, in __init__
>     self.share = Share(self.ticker)
>   File "C:\Users\Julian\Anaconda3\lib\site-packages\yahoo_finance\__init__.py", line 178, in __init__
>     self.refresh()
>   File "C:\Users\Julian\Anaconda3\lib\site-packages\yahoo_finance\__init__.py", line 142, in refresh
>     self.data_set = self._fetch()
>   File "C:\Users\Julian\Anaconda3\lib\site-packages\yahoo_finance\__init__.py", line 181, in _fetch
>     data = super(Share, self)._fetch()
>   File "C:\Users\Julian\Anaconda3\lib\site-packages\yahoo_finance\__init__.py", line 134, in _fetch
>     data = self._request(query)
>   File "C:\Users\Julian\Anaconda3\lib\site-packages\yahoo_finance\__init__.py", line 125, in _request
>     raise YQLResponseMalformedError()
> yahoo_finance.YQLResponseMalformedError: Response malformed.

Is this a known problem? Saw that there was a discussion about the console YQL being down. But there was no real answer/solution to the issue.
Also I checked that and waited for a couple of days but there is no indication, that the service is down.

This issue is new to me as I used the yahoo_finance for my scripts since maybe half a year now.
Do you have any idea what causes this problem and how to solve it?

Thank you
~Best
Julian

**Comment by aliciawyy** [comment]
I have the same problem

**Comment by prokaktus** [comment]
Already there https://github.com/lukaszbanasiak/yahoo-finance/issues/140
