### ISSUE TITLE
Is this still working?

### ISSUE THREAD

**Issue by Cividati** [lukaszbanasiak/yahoo-finance#143]
I Just wanna know if it still working.

**Comment by taxus13** [comment]
I just tried it and it fails:
`urllib.error.URLError: <urlopen error [Errno 11001] getaddrinfo failed>`

However, http://datatables.org/ is down (maybe this causes the exception), so I think this project is abandoned.

**Comment by Winning117** [comment]
This library has been abandoned, but you can use https://pypi.org/project/yfinance/ instead
