### ISSUE TITLE
Error occurs when the length of historical prices returned is greater than 365

### ISSUE THREAD

**Issue by lukaszbanasiak** [lukaszbanasiak/yahoo-finance#2]

**Comment by OrganicIrradiation** [comment]
I seem to be able to retrieve historical prices for more than 365 days (>500); however, it's not clear where the cuttoff occurs or why.  I briefly looked for limits on the 'select * from yahoo.finance.historicaldata ...' YQL command but didn't see anything that immediately jumped out.

**Comment by lukaszbanasiak** [comment]
fixed in 1.1.1 version
