### ISSUE TITLE
Output of get_info() does not match readme file.

### ISSUE THREAD

**Issue by colost8rams** [lukaszbanasiak/yahoo-finance#20]
Running:
    `import yahoo_finance as yf`
    `from pprint import pprint`
    `GE = yf.Share('GE')`
    `pprint(GE.get_info())`

yields:
    `{'CompanyName': None,`
    `'end': '2015-05-21',`
     `'start': '1962-01-02',`
     `'symbol': 'GE'}`

I was expecting to get `Industry` and `Sector` information in the returned dict.

**Comment by dezeug** [comment]
Same issue: 
{u'CompanyName': None,
 u'end': u'2015-NaN-24',
 u'start': u'1962-01-02',
 u'symbol': u'GE'}

**Comment by justinlent** [comment]
still seeing same thing

![image](https://cloud.githubusercontent.com/assets/6541022/11693555/5d20d5b8-9e5a-11e5-9166-c0f0838aed91.png)

**Comment by mavencode01** [comment]
Company name is `None` ?

	>>> yahoo = Share('YHOO')
	>>> from pprint import pprint
	>>> pprint(yahoo.get_info())
	{u'CompanyName': None,
	 u'end': u'2016-03-19',
	 u'start': u'1996-04-12',
	 u'symbol': u'YHOO'}

**Comment by balaji1359** [comment]
Any updates on this issue?

**Comment by camelCake** [comment]
```
>>> import yahoo_finance as yf
>>> from pprint import pprint
>>> GE = yf.Share('GE')
>>> pprint(GE.get_info())
{'symbol': 'GE'}

```

Looks like even less information is returned currently.

**Comment by lukaszbanasiak** [comment]
Since function returns less data from time to time I decided to remove it. https://github.com/lukaszbanasiak/yahoo-finance/pull/86

**Comment by marc-henniges** [comment]
Is there any other way to retrieve the start and end date of the time series?
Thank you

**Comment by balaji1359** [comment]
Please write me I have a solution for it @marc-henniges

**Comment by lukaszbanasiak** [comment]
@balaji1359 can you share here this with all? :) 

Now this method is returns only `{'symbol': 'YHOO'}`

**Comment by balaji1359** [comment]
nagisetty.balaji@gmail.com

**Comment by marc-henniges** [comment]
Hey @balaji1359 ,
Why don't you just post the solution here for everyone?
Thanks!
