### ISSUE TITLE
get_historical does not return complete historical data in certain date for certain stock

### ISSUE THREAD

**Issue by reg3190** [lukaszbanasiak/yahoo-finance#23]
get_historical does not return a complete set of historical data for certain stock. Take a random example for a stock in KLSE (Malaysian Stock Market Exchange) with yahoo ticker code of 5247.KL, with date from "2015-05-09" to "2015-06-26", it only returns a few days of data instead of all. Not sure if this is yahoo server issue or has something to do with the script.

Try the following code:
stock = Share("5247.KL")
print (stock.get_historical("2015-06-09","2015-06026"))

**Comment by josuebrunel** [comment]
Hello @reg3190 ,
How many result do you have ? If i'm not wrong, you were expecting 35 results. I don't think this a module related issue. It seems like Yahoo doesn't seem to have the data yet or something alike
This is the result with [mYQL](https://github.com/josuebrunel/myql) and i only have 20 results.

```json
{
    "query": {
        "count": 20, 
        "created": "2015-06-30T10:39:15Z", 
        "lang": "en-US", 
        "results": {
            "quote": [
                {
                    "Adj_Close": "3.02", 
                    "Close": "3.02", 
                    "Date": "2015-06-05", 
                    "High": "3.06", 
                    "Low": "3.02", 
                    "Open": "3.05", 
                    "Symbol": "5247.KL", 
                    "Volume": "325500"
                }, 
                {
                    "Adj_Close": "3.05", 
                    "Close": "3.05", 
                    "Date": "2015-06-04", 
                    "High": "3.07", 
                    "Low": "3.05", 
                    "Open": "3.05", 
                    "Symbol": "5247.KL", 
                    "Volume": "822600"
                }, 
                {
                    "Adj_Close": "3.05", 
                    "Close": "3.05", 
                    "Date": "2015-06-03", 
                    "High": "3.12", 
                    "Low": "3.02", 
                    "Open": "3.12", 
                    "Symbol": "5247.KL", 
                    "Volume": "619600"
                }, 
                {
                    "Adj_Close": "3.08", 
                    "Close": "3.08", 
                    "Date": "2015-06-02", 
                    "High": "3.09", 
                    "Low": "3.07", 
                    "Open": "3.08", 
                    "Symbol": "5247.KL", 
                    "Volume": "1269000"
                }, 
                {
                    "Adj_Close": "3.10", 
                    "Close": "3.10", 
                    "Date": "2015-06-01", 
                    "High": "3.14", 
                    "Low": "3.05", 
                    "Open": "3.14", 
                    "Symbol": "5247.KL", 
                    "Volume": "401400"
                }, 
                {
                    "Adj_Close": "3.14", 
                    "Close": "3.14", 
                    "Date": "2015-05-29", 
                    "High": "3.14", 
                    "Low": "3.03", 
                    "Open": "3.10", 
                    "Symbol": "5247.KL", 
                    "Volume": "1267200"
                }, 
                {
                    "Adj_Close": "3.05", 
                    "Close": "3.05", 
                    "Date": "2015-05-28", 
                    "High": "3.10", 
                    "Low": "3.05", 
                    "Open": "3.10", 
                    "Symbol": "5247.KL", 
                    "Volume": "359200"
                }, 
                {
                    "Adj_Close": "3.10", 
                    "Close": "3.10", 
                    "Date": "2015-05-27", 
                    "High": "3.10", 
                    "Low": "3.03", 
                    "Open": "3.07", 
                    "Symbol": "5247.KL", 
                    "Volume": "261700"
                }, 
                {
                    "Adj_Close": "3.07", 
                    "Close": "3.07", 
                    "Date": "2015-05-26", 
                    "High": "3.10", 
                    "Low": "3.01", 
                    "Open": "3.01", 
                    "Symbol": "5247.KL", 
                    "Volume": "517400"
                }, 
                {
                    "Adj_Close": "3.02", 
                    "Close": "3.02", 
                    "Date": "2015-05-25", 
                    "High": "3.13", 
                    "Low": "3.01", 
                    "Open": "3.13", 
                    "Symbol": "5247.KL", 
                    "Volume": "466100"
                }, 
                {
                    "Adj_Close": "3.13", 
                    "Close": "3.13", 
                    "Date": "2015-05-22", 
                    "High": "3.16", 
                    "Low": "3.10", 
                    "Open": "3.10", 
                    "Symbol": "5247.KL", 
                    "Volume": "297300"
                }, 
                {
                    "Adj_Close": "3.09", 
                    "Close": "3.09", 
                    "Date": "2015-05-21", 
                    "High": "3.16", 
                    "Low": "3.08", 
                    "Open": "3.15", 
                    "Symbol": "5247.KL", 
                    "Volume": "316800"
                }, 
                {
                    "Adj_Close": "3.15", 
                    "Close": "3.15", 
                    "Date": "2015-05-20", 
                    "High": "3.16", 
                    "Low": "3.14", 
                    "Open": "3.16", 
                    "Symbol": "5247.KL", 
                    "Volume": "203000"
                }, 
                {
                    "Adj_Close": "3.11", 
                    "Close": "3.11", 
                    "Date": "2015-05-19", 
                    "High": "3.18", 
                    "Low": "3.11", 
                    "Open": "3.18", 
                    "Symbol": "5247.KL", 
                    "Volume": "243900"
                }, 
                {
                    "Adj_Close": "3.16", 
                    "Close": "3.16", 
                    "Date": "2015-05-18", 
                    "High": "3.18", 
                    "Low": "3.15", 
                    "Open": "3.15", 
                    "Symbol": "5247.KL", 
                    "Volume": "522300"
                }, 
                {
                    "Adj_Close": "3.15", 
                    "Close": "3.15", 
                    "Date": "2015-05-15", 
                    "High": "3.15", 
                    "Low": "3.10", 
                    "Open": "3.12", 
                    "Symbol": "5247.KL", 
                    "Volume": "422300"
                }, 
                {
                    "Adj_Close": "3.12", 
                    "Close": "3.12", 
                    "Date": "2015-05-14", 
                    "High": "3.20", 
                    "Low": "3.11", 
                    "Open": "3.20", 
                    "Symbol": "5247.KL", 
                    "Volume": "561000"
                }, 
                {
                    "Adj_Close": "3.12", 
                    "Close": "3.12", 
                    "Date": "2015-05-13", 
                    "High": "3.13", 
                    "Low": "3.10", 
                    "Open": "3.13", 
                    "Symbol": "5247.KL", 
                    "Volume": "2430900"
                }, 
                {
                    "Adj_Close": "3.12", 
                    "Close": "3.12", 
                    "Date": "2015-05-12", 
                    "High": "3.20", 
                    "Low": "3.12", 
                    "Open": "3.19", 
                    "Symbol": "5247.KL", 
                    "Volume": "944300"
                }, 
                {
                    "Adj_Close": "3.19", 
                    "Close": "3.19", 
                    "Date": "2015-05-11", 
                    "High": "3.21", 
                    "Low": "3.17", 
                    "Open": "3.17", 
                    "Symbol": "5247.KL", 
                    "Volume": "1766400"
                }
            ]
        }
    }
}

```

**Comment by reg3190** [comment]
Hi Josue,
Yes, you are correct, it's not the module issue, thanks for spending time
looking into this, appreciate it.

Regards,
Kenny

On Tue, Jun 30, 2015 at 6:47 PM, Josue Kouka <notifications@github.com>
wrote:

> Hello @reg3190 <https://github.com/reg3190> ,
> How many result do you have ? If i'm not wrong, you were expecting 35
> results. I don't think this a module related issue. It seems like Yahoo
> doesn't seem to have the data yet or something alike
> This is the result with mYQL <https://github.com/josuebrunel/myql> and i
> only have 20 results.
>
> {
>     "query": {
>         "count": 20,
>         "created": "2015-06-30T10:39:15Z",
>         "lang": "en-US",
>         "results": {
>             "quote": [
>                 {
>                     "Adj_Close": "3.02",
>                     "Close": "3.02",
>                     "Date": "2015-06-05",
>                     "High": "3.06",
>                     "Low": "3.02",
>                     "Open": "3.05",
>                     "Symbol": "5247.KL",
>                     "Volume": "325500"
>                 },
>                 {
>                     "Adj_Close": "3.05",
>                     "Close": "3.05",
>                     "Date": "2015-06-04",
>                     "High": "3.07",
>                     "Low": "3.05",
>                     "Open": "3.05",
>                     "Symbol": "5247.KL",
>                     "Volume": "822600"
>                 },
>                 {
>                     "Adj_Close": "3.05",
>                     "Close": "3.05",
>                     "Date": "2015-06-03",
>                     "High": "3.12",
>                     "Low": "3.02",
>                     "Open": "3.12",
>                     "Symbol": "5247.KL",
>                     "Volume": "619600"
>                 },
>                 {
>                     "Adj_Close": "3.08",
>                     "Close": "3.08",
>                     "Date": "2015-06-02",
>                     "High": "3.09",
>                     "Low": "3.07",
>                     "Open": "3.08",
>                     "Symbol": "5247.KL",
>                     "Volume": "1269000"
>                 },
>                 {
>                     "Adj_Close": "3.10",
>                     "Close": "3.10",
>                     "Date": "2015-06-01",
>                     "High": "3.14",
>                     "Low": "3.05",
>                     "Open": "3.14",
>                     "Symbol": "5247.KL",
>                     "Volume": "401400"
>                 },
>                 {
>                     "Adj_Close": "3.14",
>                     "Close": "3.14",
>                     "Date": "2015-05-29",
>                     "High": "3.14",
>                     "Low": "3.03",
>                     "Open": "3.10",
>                     "Symbol": "5247.KL",
>                     "Volume": "1267200"
>                 },
>                 {
>                     "Adj_Close": "3.05",
>                     "Close": "3.05",
>                     "Date": "2015-05-28",
>                     "High": "3.10",
>                     "Low": "3.05",
>                     "Open": "3.10",
>                     "Symbol": "5247.KL",
>                     "Volume": "359200"
>                 },
>                 {
>                     "Adj_Close": "3.10",
>                     "Close": "3.10",
>                     "Date": "2015-05-27",
>                     "High": "3.10",
>                     "Low": "3.03",
>                     "Open": "3.07",
>                     "Symbol": "5247.KL",
>                     "Volume": "261700"
>                 },
>                 {
>                     "Adj_Close": "3.07",
>                     "Close": "3.07",
>                     "Date": "2015-05-26",
>                     "High": "3.10",
>                     "Low": "3.01",
>                     "Open": "3.01",
>                     "Symbol": "5247.KL",
>                     "Volume": "517400"
>                 },
>                 {
>                     "Adj_Close": "3.02",
>                     "Close": "3.02",
>                     "Date": "2015-05-25",
>                     "High": "3.13",
>                     "Low": "3.01",
>                     "Open": "3.13",
>                     "Symbol": "5247.KL",
>                     "Volume": "466100"
>                 },
>                 {
>                     "Adj_Close": "3.13",
>                     "Close": "3.13",
>                     "Date": "2015-05-22",
>                     "High": "3.16",
>                     "Low": "3.10",
>                     "Open": "3.10",
>                     "Symbol": "5247.KL",
>                     "Volume": "297300"
>                 },
>                 {
>                     "Adj_Close": "3.09",
>                     "Close": "3.09",
>                     "Date": "2015-05-21",
>                     "High": "3.16",
>                     "Low": "3.08",
>                     "Open": "3.15",
>                     "Symbol": "5247.KL",
>                     "Volume": "316800"
>                 },
>                 {
>                     "Adj_Close": "3.15",
>                     "Close": "3.15",
>                     "Date": "2015-05-20",
>                     "High": "3.16",
>                     "Low": "3.14",
>                     "Open": "3.16",
>                     "Symbol": "5247.KL",
>                     "Volume": "203000"
>                 },
>                 {
>                     "Adj_Close": "3.11",
>                     "Close": "3.11",
>                     "Date": "2015-05-19",
>                     "High": "3.18",
>                     "Low": "3.11",
>                     "Open": "3.18",
>                     "Symbol": "5247.KL",
>                     "Volume": "243900"
>                 },
>                 {
>                     "Adj_Close": "3.16",
>                     "Close": "3.16",
>                     "Date": "2015-05-18",
>                     "High": "3.18",
>                     "Low": "3.15",
>                     "Open": "3.15",
>                     "Symbol": "5247.KL",
>                     "Volume": "522300"
>                 },
>                 {
>                     "Adj_Close": "3.15",
>                     "Close": "3.15",
>                     "Date": "2015-05-15",
>                     "High": "3.15",
>                     "Low": "3.10",
>                     "Open": "3.12",
>                     "Symbol": "5247.KL",
>                     "Volume": "422300"
>                 },
>                 {
>                     "Adj_Close": "3.12",
>                     "Close": "3.12",
>                     "Date": "2015-05-14",
>                     "High": "3.20",
>                     "Low": "3.11",
>                     "Open": "3.20",
>                     "Symbol": "5247.KL",
>                     "Volume": "561000"
>                 },
>                 {
>                     "Adj_Close": "3.12",
>                     "Close": "3.12",
>                     "Date": "2015-05-13",
>                     "High": "3.13",
>                     "Low": "3.10",
>                     "Open": "3.13",
>                     "Symbol": "5247.KL",
>                     "Volume": "2430900"
>                 },
>                 {
>                     "Adj_Close": "3.12",
>                     "Close": "3.12",
>                     "Date": "2015-05-12",
>                     "High": "3.20",
>                     "Low": "3.12",
>                     "Open": "3.19",
>                     "Symbol": "5247.KL",
>                     "Volume": "944300"
>                 },
>                 {
>                     "Adj_Close": "3.19",
>                     "Close": "3.19",
>                     "Date": "2015-05-11",
>                     "High": "3.21",
>                     "Low": "3.17",
>                     "Open": "3.17",
>                     "Symbol": "5247.KL",
>                     "Volume": "1766400"
>                 }
>             ]
>         }
>     }
> }
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lukaszbanasiak/yahoo-finance/issues/23#issuecomment-117122064>
> .
>



-- 
Best Regards,
Kenny Oh

**Comment by josuebrunel** [comment]
@reg3190 you're welcome :wink:
