### ISSUE TITLE
Symbol not found

### ISSUE THREAD

**Issue by rdiasfreitas** [lukaszbanasiak/yahoo-finance#3]
Hi
You could raise an error, or create a status field if the symbol is not found.
The current solution is throwing an error on:

  File "build/bdist.linux-x86_64/egg/yahoo_finance/__init__.py", line 127, in _fetch
    data[u'LastTradeDateTimeUTC'] = edt_to_utc('%s %s' % (data['LastTradeDate'], data['LastTradeTime']))

Thanks

**Comment by lukaszbanasiak** [comment]
I have added:
- error lookup ab6e18556a77403cc3a204da78b3444ec14d1ab8
- rebuild query function 1336d117c2f79190ef3b7a4bfd655f547c13e449
and few other useful changes in 1.1.1 version that will do the trick

**Comment by rdiasfreitas** [comment]
Thanks!
