### ISSUE TITLE
Installing for python3

### ISSUE THREAD

**Issue by valdt** [lukaszbanasiak/yahoo-finance#32]
pip3 install yahoo-finance did ain’t work for me, could we add another paragraph for the read.me like

For python3 on some system do:
git clone http://blablalba
cd yahoo-finance
python3 setup.py install  #This part!

**Comment by lukaszbanasiak** [comment]
It's now support Python 3.3 to 3.5 https://github.com/lukaszbanasiak/yahoo-finance/pull/87
