### ISSUE TITLE
get_trade_datetime() return  "2016-03-02 21:00:00 UTC+0000"

### ISSUE THREAD

**Issue by xiaoshi10a** [lukaszbanasiak/yahoo-finance#45]
> > > yahoo = Share('YHOO')
> > > yahoo.refresh()
> > > print yahoo.get_trade_datetime()
> > > 2016-03-02 21:00:00 UTC+0000
> > > print yahoo.get_price()
> > > 32.91

The YHOO stock price in http://finance.yahoo.com/ now!
**Yahoo! Inc. (YHOO) -NasdaqGS   Watchlist
32.88 Down 0.03(0.09%) Mar 3, 4:00PM EST**

**Comment by mavencode01** [comment]
Looks like it doesn't exist anymore ?

**Comment by lukaszbanasiak** [comment]
@xiaoshi10a if this is still valid feel free to reopen
