### ISSUE TITLE
Try avg methods

### ISSUE THREAD

**Issue by morientes26** [lukaszbanasiak/yahoo-finance#49]
I have tried average method get_50day_moving_avg() and get_200day_moving_avg today but they have not worked.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'get_200day_moving_avg' is not defined

**Comment by jwallden** [comment]
I just tried both of them

`share = Share('YHOO')`
`print(share.get_50day_moving_avg())`
`print(share.get_200day_moving_avg())`

Works perfectly fine for me.

**Comment by lukaszbanasiak** [comment]
@morientes26 If this is still valid feel free to reopen this issue.
