### ISSUE TITLE
Get index data?

### ISSUE THREAD

**Issue by ralston3** [lukaszbanasiak/yahoo-finance#50]
Is it possible to get data (historical and/or present) for any of the market indexes? S&P500, DOW, NASDAQ? Trying to make comparisons between stock and index performance.

**Comment by aahmd** [comment]
Have you tried using the indices corresponding ticker symbols (i.e. .SPX; .DJIA, etc..) in combination with the get.hisotircal() method???

**Comment by ralston3** [comment]
That'll do it.
