### ISSUE TITLE
Visual Studio Intellisense - python setup.py install doesn't add lib/site-packages/yahoo-finance/ directory

### ISSUE THREAD

**Issue by joseortiz3** [lukaszbanasiak/yahoo-finance#51]
Hello,

Perhaps I'm being a python noob, but running Anaconda Python 2.7 from the Anaconda Prompt and executing "python setup.py install" on the downloaded extracted folder installs everything correctly except I do not get a "lib/site-packages/yahoo-finance/" directory inside my Anaconda directory. Without this, I can still "import yahoo_finance," but Visual Studio's Intellisense cannot create a database for the module without putting the "yahoo-finance-1.2.1/yahoo-finance" containing **init** and yql into the "site-packages" directory. This step is usually completed automatically in python installers. This way, Intellisense knows all the methods etc. of this module.

Hope this helps someone.
Jose

**Comment by joseortiz3** [comment]
Also, if anyone want's to answer this also/instead: Is there a way with this module to get the company's name given a stock symbol?
>>> yahoo = yf.Share('YHOO')
>>> yahoo.get_info()
{'start': '1996-04-12', 'symbol': 'YHOO', 'end': '2016-04-23', 'CompanyName': None}

Company name appears to not work.

**Comment by lukaszbanasiak** [comment]
@joseortiz3 try install this via pip
`pip install yahoo-finance`

**Comment by icebluesun** [comment]
Hi,
I've been having this issue today.
Would you know of a fix for it?
I'm new to python so not sure how to adjust for this issue.

Everything seems fine except for the history portion.
Error log attached below.

Dennis

[YF_Error_20160519.txt](https://github.com/lukaszbanasiak/yahoo-finance/files/273744/YF_Error_20160519.txt)

**Comment by lukaszbanasiak** [comment]
@joseortiz3 It's still occur?

@icebluesun Probably one time issue with Yahoo endpoint.
