### ISSUE TITLE
.get_historical sometimes results in a KeyError: "query"

### ISSUE THREAD

**Issue by Terpal47** [lukaszbanasiak/yahoo-finance#56]
Not sure what's causing it, but if I run the following code a few times then eventually it results in an error "yahoo_finance.YQLQueryError: Query failed with error: "'No definition found for Table yahoo.finance.historicaldata'"."
`from yahoo_finance import Share`
`index = "^IXIC"`
`index = Share(index)`
`print(index.get_historical("2016-07-20", "2016-07-21"))`

I'd be interested in hearing if others can reproduce it. I wasn't getting this error before and I've been using this API for weeks, so I'm sad to be getting this issue. FYI, ^IXIC represents the Nasdaq Composite index and is just an example, the same error occurs for other indices and regular stocks such as MSFT.

**Comment by migloo** [comment]
same here. 
Sometimes works, sometimes doesn't.

**Comment by Terpal47** [comment]
I added a few lines that changed _request in __init__.py:
```
def _request(self, query):
        for i in range(20):
            response = yql.YQLQuery().execute(query)
            try:
                _, results = response['query']['results'].popitem()
            except StopIteration:
                try:
                    raise YQLQueryError(response['error']['description'])
                except KeyError:
                    raise YQLResponseMalformedError()
            except KeyError:
                continue
            else:
                if self._is_error_in_results(results):
                    raise YQLQueryError(self._is_error_in_results(results))
                self._change_incorrect_none(results)
                return results
            break
```
It just retries up to 20 times until it gets the information it needs (usually works after just one try), but it's just a temporary workaround, probably not worth adding to repo. Also there's a risk that if something else causes a KeyError then it'll just keep retrying even though it might not make a difference. I'm afraid I don't know enough about Yahoo's API to give this a better fix...

**Comment by Terpal47** [comment]
Hmm it seems to now have been fixed, I was running some tests to see how often it'd happen and I was getting anywhere between 30 to 80% of the time per 100 queries, but now I've run around 2000 queries and I've gotten the error 0 times. I'll close this tomorrow if it stays this way.

**Comment by Terpal47** [comment]
Tested it again and it seems to have been resolved, whatever was causing the issue; likely on Yahoo's end.

**Comment by 5ai92** [comment]
I beleive the error is causing becoz the start date in getting the historical data is less than 2 days which should be atleast 2 days prior to the current date. when it meets this criteria, it works fine.
