### ISSUE TITLE
KeyError in 1.2.1 test suite

### ISSUE THREAD

**Issue by TheChymera** [lukaszbanasiak/yahoo-finance#70]
In addition to [other errors](https://github.com/lukaszbanasiak/yahoo-finance/issues/68#issuecomment-251528594) I am getting the following error when running the test suite for 1.2.1.

```
======================================================================
ERROR: test_get_info (__main__.TestShare)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/test_yahoo.py", line 24, in test_get_info
    self.assertEqual(info['start'], '1996-04-12')
KeyError: 'start'
```

It is interesting that this [does not happen](https://github.com/lukaszbanasiak/yahoo-finance/issues/68#issuecomment-251527889) on the master HEAD. It could be that the JSON error is masking this, or that this has been solved.

**Comment by lukaszbanasiak** [comment]
Duplicate with #20
