### ISSUE TITLE
The remote server returned an error: (400) Bad Request

### ISSUE THREAD

**Issue by srinuprty** [lukaszbanasiak/yahoo-finance#78]
Having connection issues with rest call, this was working yesterday

Rest Url:
http://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20yahoo.finance.quotes%20where%20symbol%20in%20("YHOO")&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys

Error:
The remote server returned an error: (400) Bad Request.

When I tried in YQL console, it worked. however in browser it did not and get the following exception.

`<error xmlns:yahoo="http://www.yahooapis.com/v1/base.rng" yahoo:lang="en-US">
<diagnostics>
<url error="Connect Failure" execution-start-time="0" execution-stop-time="4004" execution-time="4004">
<![CDATA[
http://www.datatables.org/yahoo/finance/yahoo.finance.quotes.xml
]]>
</url>
<url error="Connect Failure" execution-start-time="0" execution-stop-time="4004" execution-time="4004">
<![CDATA[
http://www.datatables.org/yahoo/finance/yahoo.finance.quotes.xml
]]>
</url>
</diagnostics>
<description>No definition found for Table yahoo.finance.quotes</description>
</error>`

Please help. Thanks in advance.

**Comment by Rudd-O** [comment]
Same problem here.

**Comment by lukaszbanasiak** [comment]
Backend for the community tables that power YQL is http://datatables.org/. If this service is down you will receive error like that. You can monitor this service via https://www.datatables.org/healthchecker/
