### ISSUE TITLE
Is the returned stock info real-time?

### ISSUE THREAD

**Issue by hongtaocai** [lukaszbanasiak/yahoo-finance#8]
I found the returned data from yahoo-finance is 15 min late than the market. Is this an expected behavior?

**Comment by lukaszbanasiak** [comment]
15 minutes after the opening, prices have changed in YQL. The data comes from Yahoo! YQL so I think is Yahoo! limitations. Perhaps Yahoo offers paid subscriptions for this purpose

https://developer.yahoo.com/yql/console/?q=show%20tables&env=store://datatables.org/alltableswithkeys#h=select+*+from+yahoo.finance.quotes+where+symbol+%3D+%22YHOO%22

**Comment by hongtaocai** [comment]
Thank you!
