### ISSUE TITLE
get_info() returns symbol only

### ISSUE THREAD

**Issue by marc-henniges** [lukaszbanasiak/yahoo-finance#85]
Hi,

while this used to work fine, it now doesn't anymore:
```
In [1]: from yahoo_finance import Share
In [2]: test = Share('YHOO')
In [3]: test.get_info()
Out[3]: {'symbol': 'YHOO'}
```

Before, the get_info returned a lot more, as specified on the website:
```
>>> from pprint import pprint
>>> pprint(yahoo.get_info())
{u'FullTimeEmployees': u'12200',
 u'Industry': u'Internet Information Providers',
 u'Sector': u'Technology',
 u'end': u'2014-05-03',
 u'start': u'1996-04-12',
 u'symbol': u'YHOO'}
```

Did I miss something?

Thanks

**Comment by lukaszbanasiak** [comment]
@marc-henniges yes, Yahoo don't provide any more those informations. Duplicated issue https://github.com/lukaszbanasiak/yahoo-finance/issues/20
