### ISSUE TITLE
I have  a new script to get the data in an easy way. 

### ISSUE THREAD

**Issue by balaji1359** [lukaszbanasiak/yahoo-finance#89]
Please contact me.

**Comment by lukaszbanasiak** [comment]
@balaji1359 same story like here https://github.com/lukaszbanasiak/yahoo-finance/issues/20#issuecomment-261496368 can you share this. Issues are for questions, report problems or discuss about enhancements. I don;t see here anything from those 3.

Please update description, till that time will be closed.
