### ISSUE TITLE
get_info: "AttributeError: 'Share' object has no attribute 'get_info'"

### ISSUE THREAD

**Issue by Markatron** [lukaszbanasiak/yahoo-finance#94]
get_info doesn't seem to be working. Is there any chance this has been removed? Any ideas?

Code:
```
from yahoo_finance import Share
yahoo_info = Share('YHOO')
yahoo_info.get_info()
```

Outputs:
`AttributeError: 'Share' object has no attribute 'get_info'`

**Comment by lukaszbanasiak** [comment]
@Markatron yes, was removed in 1.4.0 version https://github.com/lukaszbanasiak/yahoo-finance/releases/tag/1.4.0
